neutronimaging/imagingsuite

applications/muhrec3/src/muhrecmainwindow.cpp
applications/muhrec3/src/muhrecmainwindow.h
frameworks/tomography/Framework/ReconFramework/src/ReconHelpers.cpp

Fixed the updating issues for projection sliders. Many crashed are prevented :-)

Issue25 updateindex

---

applications/muhrec3/src/muhrecmainwindow.cpp
core/kipl/kipl/qt/kipl.pro
core/modules/ReaderConfig/ReaderConfig.pro
frameworks/tomography/Framework/ReconAlgorithms/ReconAlgorithms/ReconAlgorithms.pro
frameworks/tomography/Framework/ReconFramework/qt/ReconFramework/ReconFramework.pro
frameworks/tomography/Framework/ReconFramework/src/ProjectionReader.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/qt/StdPreprocModulesGUI/StdPreprocModulesGUI.pro

Ne xus win

---

applications/muhrec3/src/muhrecmainwindow.cpp

changes on first and last slices to prevent error y1<y0

Issue21 new config

---

GUI/qt/QtAddons/QtAddons.pro
GUI/qt/QtAddons/imageviewerwidget.cpp
GUI/qt/QtAddons/imageviewerwidget.h
GUI/qt/QtAddons/uxroiwidget.cpp
GUI/qt/QtAddons/uxroiwidget.h
GUI/qt/QtAddons/uxroiwidget.ui
GUI/qt/WidgetTests/WidgetTests.pro
GUI/qt/WidgetTests/mainwindow.cpp
GUI/qt/WidgetTests/mainwindow.ui
applications/muhrec3/src/piercingpointdialog.cpp

Implemented a new widget to handle rois more consistently and to improve UX

Issue54 ro iwidget

---

applications/muhrec3/src/muhrec3.pro
applications/muhrec3/src/muhrecmainwindow.cpp
applications/muhrec3/src/muhrecmainwindow.h
applications/muhrec3/src/referencefiledlg.cpp
applications/muhrec3/src/referencefiledlg.h
applications/muhrec3/src/referencefiledlg.ui
core/kipl/UnitTests/tDirAnalysis/tst_tdiranalysistest.cpp
core/kipl/kipl/include/io/DirAnalyzer.h
core/kipl/kipl/src/io/DirAnalyzer.cpp
core/kipl/kipl/src/strings/filenames.cpp

The reference file suggestion dialog is implemented. It seems to work well. The changes affect kipl/io/DirAnalyzer and the Muhrec application.

Issue20 1 folders

---

GUI/qt/QtAddons/QtAddons.pro
GUI/qt/QtAddons/loggingdialog.cpp
GUI/qt/QtAddons/loggingdialog.h
GUI/qt/QtAddons/loggingdialog.ui
GUI/qt/QtAddons/qtlogviewer.ui
GUI/qt/WidgetTests/mainwindow.cpp
GUI/qt/WidgetTests/mainwindow.h
GUI/qt/WidgetTests/mainwindow.ui
applications/muhrec3/src/muhrecmainwindow.cpp
applications/muhrec3/src/muhrecmainwindow.h
applications/muhrec3/src/muhrecmainwindow.ui
core/kipl/kipl/src/io/io_tiff.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconFactory.cpp

Added a logging dialog to replace the log tab in the main workflow.

Issue70 logging dlg

---

applications/muhrec3/deploymuhrec3_ubuntu_withQT.sh
applications/muhrec3/src/configuregeometrydialog.cpp
applications/muhrec3/src/muhrecmainwindow.cpp
applications/muhrec3/src/muhrecmainwindow.h
applications/muhrec3/src/muhrecmainwindow.ui
frameworks/tomography/Framework/ReconFramework/include/ReconConfig.h
frameworks/tomography/Framework/ReconFramework/src/ReconConfig.cpp

I would like to merge.
Issues addressed: #66, #67, #79

Issue66 g rangles

---

frameworks/tomography/Preprocessing/StdPreprocModules/src/NormPlugins.cpp

Bug search in vane... it was the data.
However, I used the occasion to clean up the code and to add progress bar interaction.

Some code cleanup to remove warnings (signed/unsigned)

---

applications/CLI/muhrecCLI/stdafx.cpp
applications/CLI/muhrecCLI/stdafx.h
applications/muhrec3/src/muhrecmainwindow.cpp
applications/muhrec3/src/muhrecmainwindow.h
applications/muhrec3/src/muhrecmainwindow.ui
build/windows/removebuild.bat

Fixed some GUI related adjustments according to issue #99

Issue99 guiadjustments

---

core/algorithms/ImagingQAAlgorithms/resolutionestimators.cpp
core/algorithms/ImagingQAAlgorithms/resolutionestimators.h
core/algorithms/UnitTests/tImagingQAAlgorithms/tst_timagingqaalgorithmstest.cpp
core/kipl/UnitTests/tKiplMath/tst_tkiplmathtest.cpp
core/kipl/kipl/include/math/nonlinfit.h
core/kipl/kipl/include/stltools/stlvecmath.h
core/kipl/kipl/src/math/nonlinfit.cpp

Updated non-linear function fitting

Ballanalysis

---

applications/CLI/verticalslicer/.gitignore
applications/CLI/verticalslicer/deployverticalslicer_mac.sh
applications/CLI/verticalslicer/deployverticalslicer_win.bat
applications/CLI/verticalslicer/main.cpp
applications/CLI/verticalslicer/verticalslicer.pro

Implemented a CLI tool to extract the central slice. Good for automation. It runs on Mac and Windows

Verticalslicer

---

applications/muhrec/src/muhrecmainwindow.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.cpp

solved by removing the interactor from fdkReconBase

pull request on issue 144

---

GUI/qt/QtAddons/uxroiwidget.cpp
applications/CLI/multiframesplitter/main.cpp
applications/muhrec/src/configuregeometrydialog.cpp
applications/muhrec/src/muhrecmainwindow.cpp
core/kipl/kipl/include/io/io_nexus.h
core/kipl/kipl/include/io/io_tiff.h
core/modules/ReaderConfig/imagewriter.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconConfig.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconHelpers.cpp

ROI handling is fixed for matrix roi and slice selection

Issue125 fix roi

---

GUI/qt/QtAddons/QtAddons.pro
GUI/qt/QtAddons/imageviewerinfodialog.cpp
GUI/qt/QtAddons/imageviewerinfodialog.ui
GUI/qt/QtAddons/imageviewerwidget.cpp
GUI/qt/QtAddons/imageviewerwidget.h
GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtAddons/plotwidget.h
GUI/qt/QtAddons/setgraylevelsdlg.cpp
GUI/qt/QtAddons/setgraylevelsdlg.h
GUI/qt/QtAddons/setgraylevelsdlg.ui

Solves issue #179 
Revised ImageInfodialog to use PlotWidget
Added hide plot functionality in the PlotWidget

Added a new image level dialog based on designer form

---

frameworks/imageprocessing/modules/ImagingModules/src/imagingmodules.cpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.cpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.h
frameworks/imageprocessing/modules/ImagingModulesGui/ImagingModulesGui/ImagingModulesGui.pro
frameworks/imageprocessing/modules/ImagingModulesGui/ImagingModulesGui/imagingmodulesgui.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/ImagingModulesGui/morphspotcleandlg.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/ImagingModulesGui/morphspotcleandlg.h
frameworks/imageprocessing/modules/ImagingModulesGui/ImagingModulesGui/morphspotcleandlg.ui

With this branch we add the MorphSpotClean module with Dlg in KipTool

Issue167 morph spot

---

applications/kiptool/deploykiptool_mac.sh

with this merge we update the deployment file for KipTool in Mac

Issue155 deploy kip tool mac

---

frameworks/imageprocessing/modules/ClassificationModules/src/BasicThreshold.cpp
frameworks/imageprocessing/modules/ClassificationModules/src/BasicThreshold.h
frameworks/imageprocessing/modules/ClassificationModules/src/ClassificationModules.cpp
frameworks/imageprocessing/modules/ClassificationModules/src/DoubleThreshold.cpp
frameworks/imageprocessing/modules/ClassificationModules/src/DoubleThreshold.h
frameworks/imageprocessing/modules/ClassificationModulesGUI/src/basicthresholddlg.cpp

with this branch we add the progress bar for the basic threshold module

issue182 adding progress bar to Basic Threshold

---

GUI/qt/QtAddons/QtAddons.pro
GUI/qt/QtAddons/callout.cpp
GUI/qt/QtAddons/callout.h
GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtAddons/plotwidget.h

Added support for plot tooltips in plotwidget. This implements issue #191.

Added tooltip information when hoovering on a curve.

---

GUI/qt/QtAddons/QtAddons.pro
GUI/qt/QtAddons/facestyles.cpp
GUI/qt/QtAddons/facestyles.h
applications/muhrec/deploymuhrec_win.bat
applications/muhrec/src/main.cpp
applications/muhrec/src/muhrec.pro
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.ui
applications/muhrec/src/recondialog.cpp
core/modules/ModuleConfig/src/ConfigBase.cpp
frameworks/tomography/Framework/ReconFramework/include/ReconConfig.h
frameworks/tomography/Framework/ReconFramework/src/ReconConfig.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp

Main issue: A buffer overwrite bug that set cone beam every time parallel beam was requested. This was happening the imgreader. getdims was called.
Added view splitter between projection and slice view.
Moved dark style to function in QtAddons.

Issue200 ro ierror

---

applications/kiptool/src/Reslicer.cpp
applications/kiptool/src/Reslicer.h
applications/kiptool/src/reslicerdialog.cpp
applications/kiptool/src/reslicerdialog.h
applications/kiptool/src/reslicerdialog.ui

Part I of conversion tools. The reslicer is in a useful condition. Some functionality was hidden from the UI.

Fixed missing functionality in the reslice tool.

---

frameworks/imageprocessing/modules/ImagingModules/src/bblognorm.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/bblognormdlg.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/bblognormdlg.ui

With this branch the mirror and rotation options defined in the main window are propagated into the ref images loaded by the BBLogNorm

Issue222 bb mirror

---

GUI/qt/QtAddons/facestyles.cpp
GUI/qt/QtAddons/uxroiwidget.cpp
GUI/qt/QtImaging/QtImaging.pro
GUI/qt/WidgetTests/mainwindow.cpp
applications/muhrec/scripts/muhrec
applications/muhrec/src/muhrec.pro
core/kipl/kipl/src/filters/nonlocalmeans.cpp

The fix is now tested on Win, Lin, Mac

Issue220 missing ro irect

---

core/algorithms/ImagingAlgorithms/src/ReferenceImageCorrection.cpp
core/kipl/UnitTests/tkiplmorphologytest/tst_kiplmorphologytest.cpp
core/kipl/kipl/include/morphology/core/repairhole.hpp
core/kipl/kipl/include/morphology/repairhole.h
core/kipl/kipl/qt/kipl.pro

The repair hole algorithm fixed much of the starvation artifacts.

Issue219 b bstarvation

---

GUI/qt/QtImaging/QtImaging.pro
build/build_all.sh
build/loghistory.sh
core/kipl/kipl/include/scalespace/lambdaest.h
core/modules/ReaderConfig/ReaderConfig.pro
deploy/linux/deploykiptool_ubuntu_withQT.sh

generalized version of Qt to deploy the kiptool application
some small modification to build KipTool in linux 1804

pull request for KipTool_Ubuntu1804

---

applications/kiptool/src/kiptoolmainwindow.cpp

now creating .imagintools if not already exisiting

Kip tool ubuntu1804

---

applications/kiptool/src/reslicerdialog.cpp

Fixed the crashing located in the check for image dims

---

GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtAddons/plotwidget.h

Feature is implemented and tested on M,W,L

Issue186 save plot data

---

.gitignore
applications/muhrec/src/globalsettingsdialog.cpp
applications/muhrec/src/globalsettingsdialog.ui
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.h
applications/muhrec/src/muhrecmainwindow.ui
core/kipl/kipl/include/algorithms/datavalidator.h
core/kipl/kipl/qt/kipl.pro
frameworks/tomography/Framework/ReconFramework/include/ReconConfig.h
frameworks/tomography/Framework/ReconFramework/include/ReconEngine.h
frameworks/tomography/Framework/ReconFramework/src/ReconConfig.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/ProjectionFilter.cpp

This is an intermediate pull request to merge the data validity check (count nans and infs) in the recon engine into master. I think this is a good feature in general. 
The branch should continue until we find the reason for the boundary inf/nans between the blocks.

Issue254 na n slices

---

deploy/linux/deploykiptool_ubuntu_withQT.sh
deploy/linux/deploymuhrec_ubuntu_withQT.sh

with this branch the qt version for Linux is generalized (however it is expecting a version format of the type xx.x) for both KipTool and MuhRec. At the end of Muhrec deployment automatic packaging is also added.

Qt deploy linux

---

applications/CLI/multiframesplitter/main.cpp

Multi-frame splitter crashed when called from python. Added exception handling to improve troubleshooting with python scripts. The program doesn't crash when wrong parameters are provided.

Added exception handling to improve troubleshooting with python

---

frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.cpp

added coefficients to the ramp filter, this appears to solve the residual scale factor error on the computed attenuation coefficients when using FDK.

Issue230 fdk att coeff

---

GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtImaging/QtImaging.pro
applications/muhrec/Resources/defaults_linux.xml
applications/muhrec/Resources/defaults_mac.xml
applications/muhrec/Resources/defaults_windows.xml
core/algorithms/ImagingAlgorithms/include/MorphSpotClean.h
core/algorithms/ImagingAlgorithms/include/SpotClean.h
core/algorithms/ImagingAlgorithms/src/MorphSpotClean.cpp
core/algorithms/ImagingAlgorithms/src/SpotClean.cpp
core/kipl/kipl/include/morphology/core/repairhole.hpp
core/kipl/kipl/include/morphology/morphgeo.h
core/kipl/kipl/include/segmentation/thresholds.h
deploy/mac/deploy_muhrec_mac_debug.sh
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.cpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.h
frameworks/imageprocessing/modules/ImagingModulesGui/src/morphspotcleandlg.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/morphspotcleandlg.h
frameworks/imageprocessing/modules/ImagingModulesGui/src/morphspotcleandlg.ui
frameworks/tomography/Preprocessing/StdPreprocModules/include/MorphSpotCleanModule.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/SpotClean2.h
frameworks/tomography/Preprocessing/StdPreprocModules/src/MorphSpotCleanModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/SpotClean2.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.h
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.ui

- Added support for separate thresholds
- Did some improvement on the detection precision.

Issue277 rev spot clean

---

GUI/qt/QtImaging/QtImaging.pro
applications/kiptool/src/ImagingToolConfig.cpp
applications/kiptool/src/ImagingToolConfig.h
applications/kiptool/src/fileconversiondialog.cpp
applications/kiptool/src/fileconversiondialog.ui
applications/muhrec/Resources/defaults_linux.xml
applications/muhrec/Resources/defaults_mac.xml
applications/muhrec/Resources/defaults_windows.xml
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.ui
core/kipl/kipl/include/io/core/io_fits.hpp
core/kipl/kipl/include/io/io_nexus.h
core/modules/ModuleConfig/include/ConfigBase.h
core/modules/ModuleConfig/src/ConfigBase.cpp
core/modules/ReaderConfig/buildfilelist.cpp
core/modules/ReaderConfig/buildfilelist.h
core/modules/UnitTests/tReaderConfig/tReaderConfig.pro
core/modules/UnitTests/tReaderConfig/tst_treaderconfigtest.cpp
external/cpext2lib.sh
frameworks/tomography/Backprojectors/StdBackProjectors/src/StdBackProjectorBase.cpp
frameworks/tomography/Framework/ReconFramework/include/ReconConfig.h
frameworks/tomography/Framework/ReconFramework/include/ReconHelpers.h
frameworks/tomography/Framework/ReconFramework/src/ReconConfig.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconHelpers.cpp
frameworks/tomography/UnitTests/tFrameWork/tFrameWork.pro
frameworks/tomography/UnitTests/tFrameWork/tst_frameworktest.cpp

Golden ratio variable start index implemented

Issue280 goldenstart

---

GUI/qt/QtImaging/QtImaging.pro
GUI/qt/QtImaging/pixelsizedlg.ui
applications/muhrec/src/muhrec.pro
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.h
applications/muhrec/src/muhrecmainwindow.ui
deploy/mac/deploy_muhrec_mac_debug.sh
deploy/win/deploymuhrec_win.bat
frameworks/tomography/Backprojectors/StdBackProjectors/include/StdBackProjectors.h

Added pixel size estimator and slider boxes

Issue276 pix size est

---

GUI/qt/QtImaging/QtImaging.pro
GUI/qt/QtImaging/pixelsizedlg.cpp
GUI/qt/QtImaging/pixelsizedlg.h
applications/muhrec/src/muhrecmainwindow.cpp
core/kipl/kipl/include/filters/medianfilter.h
core/kipl/kipl/include/math/core/linfit.hpp
core/kipl/kipl/include/math/linfit.h

Accuracy increased radically. Is insensitive to line tilts.

Implemented edge line fit in the pixel size estimator.

---

applications/muhrec/Resources/defaults_linux.xml
applications/muhrec/Resources/defaults_mac.xml
applications/muhrec/Resources/defaults_windows.xml
applications/muhrec/src/configuregeometrydialog.cpp
applications/muhrec/src/configuregeometrydialog.h
applications/muhrec/src/configuregeometrydialog.ui
core/algorithms/ImagingAlgorithms/include/MorphSpotClean.h
core/algorithms/ImagingAlgorithms/include/tomocenter.h
core/algorithms/ImagingAlgorithms/qt/ImagingAlgorithms/ImagingAlgorithms.pro
core/algorithms/ImagingAlgorithms/src/MorphSpotClean.cpp
core/algorithms/ImagingAlgorithms/src/tomocenter.cpp
core/kipl/UnitTests/tLinFit/tLinFit.pro
core/kipl/UnitTests/tLinFit/tst_tlinfittest.cpp
core/kipl/kipl/include/base/core/tpermuteimage.hpp
core/kipl/kipl/include/math/core/linfit.hpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.cpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.h
frameworks/imageprocessing/modules/ImagingModulesGui/src/morphspotcleandlg.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/morphspotcleandlg.h
frameworks/imageprocessing/modules/ImagingModulesGui/src/morphspotcleandlg.ui
frameworks/tomography/Preprocessing/StdPreprocModules/include/MorphSpotCleanModule.h
frameworks/tomography/Preprocessing/StdPreprocModules/src/MorphSpotCleanModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.h
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.ui

Issue281 co rdlg

---

applications/muhrec/src/piercingpointdialog.cpp
frameworks/tomography/Framework/ReconFramework/include/ProjectionReader.h

Added exception handling for the file loading. Error dialog appears instead of crash.

Fixed crashing PP dialog

---

.gitignore
GUI/qt/QtAddons/imageviewerwidget.cpp
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.h
applications/muhrec/src/muhrecmainwindow.ui

- Added radiobuttons for the CBCT distances
- Added plus marker for the piercing point
- Set slice viewer combo to XY after recon

Implemented issue 295

---

applications/muhrec/src/findskiplistdialog.cpp
applications/muhrec/src/findskiplistdialog.h
applications/muhrec/src/findskiplistdialog.ui

Added an update plot button when the number of skipped exceed ten projection. This solves issue #315.

Skip list updated

---

core/algorithms/ImagingAlgorithms/include/PolynomialCorrection.h
core/algorithms/ImagingAlgorithms/src/PolynomialCorrection.cpp
core/algorithms/UnitTests/tImagingAlgorithms/tst_testImagingAlgorithms.cpp
core/kipl/kipl/include/strings/string2array.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/PolynomialCorrectionModule.h
frameworks/tomography/Preprocessing/StdPreprocModules/src/PolynomialCorrectionModule.cpp

Added default parameters for a 3rd order polynomial
Added unit test
Added methods needed for the test
Revised the polynomial module to use the correction class instead of copied duplicated code.

Added default parameters for a 3rd order polynomial

---

applications/kiptool/src/Fits2Tif.cpp
applications/kiptool/src/fileconversiondialog.cpp
applications/kiptool/src/kiptoolmainwindow.cpp
applications/kiptool/src/kiptoolmainwindow.ui
core/kipl/kipl/include/io/io_stack.h
core/kipl/kipl/src/io/io_stack.cpp
frameworks/imageprocessing/ProcessFramework/src/KiplEngine.cpp
frameworks/imageprocessing/modules/ImagingModules/src/bblognorm.cpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.cpp
frameworks/imageprocessing/modules/ImagingModules/src/morphspotcleanmodule.h
frameworks/imageprocessing/modules/ImagingModules/src/ringcleanmodule.cpp
frameworks/imageprocessing/modules/ImagingModules/src/ringcleanmodule.h
frameworks/imageprocessing/modules/ImagingModules/src/stripefiltermodule.cpp
frameworks/imageprocessing/modules/ImagingModules/src/stripefiltermodule.h
frameworks/imageprocessing/modules/ImagingModulesGui/src/WaveletRingCleanDlg.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/WaveletRingCleanDlg.h

Added suppoort to save 16-bit multi-frame.

Issue322 slice2vol

---

core/algorithms/ImagingAlgorithms/include/ReferenceImageCorrection.h
core/algorithms/ImagingAlgorithms/src/ReferenceImageCorrection.cpp
frameworks/imageprocessing/modules/ImagingModules/src/bblognorm.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/bblognormdlg.cpp

cleaned up a bit the code. corrected error preventing to run the module to run without the image roi.
This possibly solves issues 318 and 291

Correction of bugs of BBmodule in KipTool

---

GUI/qt/QtAddons/imagepainter.cpp
core/kipl/UnitTests/tKiplMath/tst_tkiplmathtest.cpp
core/kipl/kipl/include/math/core/image_statistics.hpp
core/kipl/kipl/include/math/image_statistics.h

Implemented the missing feature.

Issue340 viewer inf na n

---

GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtAddons/plotwidget.h

Added the axis labels. Issue 343 is not completed.

Added axis labels

---

GUI/qt/QtAddons/plotwidget.cpp
core/algorithms/ImagingQAAlgorithms/contrastsampleanalysis.cpp
core/algorithms/ImagingQAAlgorithms/contrastsampleanalysis.h
core/kipl/UnitTests/tSTLVectorOperations/.gitignore
core/kipl/UnitTests/tSTLVectorOperations/tSTLVectorOperations.pro
core/kipl/UnitTests/tSTLVectorOperations/tst_stlvecoperations.cpp
core/kipl/kipl/include/base/roi.h
core/kipl/kipl/include/base/thistogram.h
core/kipl/kipl/include/math/core/image_statistics.hpp
core/kipl/kipl/include/morphology/core/morphextrema.hpp
core/kipl/kipl/include/stltools/stlvecmath.h
core/kipl/kipl/include/stltools/watershedstl.h
core/kipl/kipl/src/base/core/histogram.cpp
core/kipl/kipl/src/base/roi.cpp
core/kipl/kipl/src/segmentation/wsthres.cpp
core/modules/ModuleConfig/include/ModuleConfig.h
core/modules/ModuleConfig/src/ModuleConfig.cpp
core/modules/ReaderConfig/readerexception.cpp
core/modules/ReaderConfig/readerexception.h

Fixed contrast analysis class. Some supporting functions/classes needed to be adjusted.

Issue235 contrast

---

GUI/qt/QtAddons/QtAddons.pro
GUI/qt/QtAddons/roiitemdlg.cpp
GUI/qt/QtAddons/roiitemdlg.h
GUI/qt/QtAddons/roiitemdlg.ui
GUI/qt/QtAddons/roimanager.cpp
GUI/qt/QtAddons/roimanager.h
GUI/qt/WidgetTests/mainwindow.cpp
core/algorithms/ImagingQAAlgorithms/ballassemblyanalysis.cpp
core/algorithms/ImagingQAAlgorithms/ballassemblyanalysis.h
core/kipl/kipl/include/base/roi.h
core/kipl/kipl/src/base/roi.cpp

ROI labels are now better supported 
A dialog to edit roi items in the roi managed was added.

Revised roi labels

---

GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtAddons/plotwidget.h

The items of issue #343 have been implemented.

Added support for generic plot series.

---

core/kipl/UnitTests/tKiplMath/tst_tkiplmathtest.cpp
core/kipl/kipl/include/math/gradient.h
core/kipl/kipl/qt/kipl.pro
core/kipl/kipl/src/math/gradient.cpp

In this branch I have added in kipl math an implementation of the numerical gradient for a 1D signal. This will be used in ToFimaging for the simplified edge fitting (Gaussian fit on the signal gradient)

Issue352 numericalgradient

---

core/kipl/kipl/include/math/mathconstants.h

In this branch I have added the neutron mass and the Planck constant that I use in the TOFImagingAlgorithm lib

Issue360 mathconstants

---

applications/muhrec/src/muhrecmainwindow.cpp
core/kipl/kipl/include/io/io_nexus.h

An extra check if the file still exists and delete if there was added. It works now.

Added extra check if the config is still present

---

core/algorithms/ImagingAlgorithms/include/ImagingException.h
core/algorithms/ImagingAlgorithms/src/ImagingException.cpp
core/algorithms/ImagingAlgorithms/src/StripeFilter.cpp
core/algorithms/UnitTests/tImagingAlgorithms/tst_testImagingAlgorithms.cpp

Problem fixed and tested in muhrec. Uninitialized buffer copy caused the problem.

Fixed the crash bug of stripe filter.

---

core/algorithms/ImagingAlgorithms/src/ReferenceImageCorrection.cpp
frameworks/imageprocessing/modules/ImagingModules/src/bblognorm.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/bblognormdlg.cpp
frameworks/imageprocessing/modules/ImagingModulesGui/src/bblognormdlg.h
frameworks/imageprocessing/modules/ImagingModulesGui/src/bblognormdlg.ui
frameworks/tomography/Preprocessing/StdPreprocModules/src/bblognorm.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/bblognormdlg.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/bblognormdlg.h
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/bblognormdlg.ui

more exception handling added.
small improvement in the dialog for the BB module in the external background cases.
All tested and working in all platforms.

Issue374 segm excep

---

build/build_all.sh
build/build_lmfit.sh
build/windows/build_all.bat

build scripts for tofimagingalgortihms and dependencies are added in build_all.
This should solve issue #396 in imagingsuite and contributes to solve issue #18 in ToFImaging

Issue396 build tof

---

GUI/qt/QtModuleConfigure/ModuleConfigurator.cpp
GUI/qt/QtModuleConfigure/ModuleConfigurator.h
applications/muhrec/src/PreProcModuleConfigurator.cpp
applications/muhrec/src/PreProcModuleConfigurator.h
applications/muhrec/src/moduleconfigprogressdialog.cpp
applications/muhrec/src/moduleconfigprogressdialog.h
applications/muhrec/src/moduleconfigprogressdialog.ui
applications/muhrec/src/muhrec.pro
applications/muhrec/src/muhrecmainwindow.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/NormPlugins.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.ui

Fixed issue #392. 
Added progress dialog to the preprocchain configurator.

Issue392 module list config data

---

applications/kiptool/src/imagingmoduleconfigurator.cpp
frameworks/imageprocessing/ProcessFramework/src/KiplEngine.cpp

Issue solved and some c++11 restructuring

Fixed issue #412 Config widget doesn't open dialog.

---

core/algorithms/ImagingAlgorithms/src/projectionfilter.cpp
core/algorithms/ImagingQAAlgorithms/contrastsampleanalysis.cpp
core/kipl/UnitTests/tKIPLTimers/.gitignore
core/kipl/UnitTests/tKIPLTimers/tKIPLTimers.pro
core/kipl/UnitTests/tKIPLTimers/tst_timertests.cpp
core/kipl/kipl/include/profile/Timer.h
core/kipl/kipl/include/stltools/stlvecmath.h
core/kipl/kipl/src/profile/Timer.cpp
core/modules/ModuleConfig/include/ProcessModuleBase.h
core/modules/ReaderConfig/imagereader.h
frameworks/tomography/Framework/ReconFramework/include/BackProjectorModuleBase.h
frameworks/tomography/Framework/ReconFramework/include/ProjectionReader.h
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp

- Implemented a new timer that reports wall time without openMP issue #369. 
- First attempt to fix issue #418.

Issue369 timers

---

applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/referencefiledlg.cpp
frameworks/tomography/Framework/ReconFramework/src/ProjectionReader.cpp

Added 'di' as name for dark current images.

Removed log messages while browsing projections. 

---

applications/muhrec/src/piercingpointdialog.ui
core/algorithms/ImagingAlgorithms/src/averageimage.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/FullLogNormDlg.ui

Fixed some issues detected during release test

---

applications/CLI/andor_dat2tif/dat2tif/dat2tif.pro
applications/CLI/andor_dat2tif/dat2tif/main.cpp
applications/CLI/andor_dat2tif/dat2tif/mainwindow.cpp
applications/CLI/kiptoolCLI/QtKipToolCLI/qtkiptoolcli.cpp
applications/CLI/multiframesplitter/main.cpp
applications/CLI/slices2volume/slice2vol.cpp
applications/CLI/verticalslicer/main.cpp
applications/CLIBundle.pro
applications/kiptool/src/ImageIO.cpp
applications/muhrec/src/main.cpp
frameworks/imageprocessing/ProcessFramework/include/KiplProcessConfig.h

Updated CLI applications to supprt stl vectors

Updated CLI tools to new stl  containers

---

GUI/qt/QtAddons/imagepainter.cpp
GUI/qt/QtAddons/imagepainter.h
GUI/qt/QtAddons/imageviewerwidget.cpp
GUI/qt/QtAddons/imageviewerwidget.h
GUI/qt/QtAddons/roimanager.cpp
GUI/qt/QtAddons/roimanager.h
GUI/qt/QtAddons/roimanager.ui
GUI/qt/QtAddons/setgraylevelsdlg.cpp
core/algorithms/ImagingQAAlgorithms/contrastsampleanalysis.cpp
core/algorithms/ImagingQAAlgorithms/resolutionestimators.cpp
core/kipl/UnitTests/tKiplMath/tst_tkiplmathtest.cpp
core/kipl/kipl/include/base/core/timage.hpp
core/kipl/kipl/include/io/io_tiff.h
core/kipl/kipl/include/math/nonlinfit.h
core/kipl/kipl/src/base/core/histogram.cpp
core/kipl/kipl/src/math/nonlinfit.cpp
core/modules/ReaderConfig/imagereader.cpp
core/modules/ReaderGUI/readerform.cpp

- Levenberg-Marquardt fit uses armadillo, partly issue #356
- Fixed ROI manager crashing
- Added save the view in imageviewer
- Fixed file mask in reader GUI
- Imageviewer histogram not so sensitive to inf and nan.

Issue18 edge analysis

---

applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.ui
core/kipl/kipl/include/math/mathfunctions.h
frameworks/tomography/Framework/ReconFramework/include/ReconConfig.h
frameworks/tomography/Framework/ReconFramework/python/GoldenScanSequence.ipynb
frameworks/tomography/Framework/ReconFramework/src/ReconConfig.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconHelpers.cpp
frameworks/tomography/UnitTests/tFrameWork/tst_frameworktest.cpp

The golden ratio is now updated.

Issue446 goldenratio

---

applications/muhrec/src/configuregeometrydialog.cpp
applications/muhrec/src/configuregeometrydialog.ui
applications/muhrec/src/muhrecmainwindow.ui
core/algorithms/ImagingAlgorithms/src/averageimage.cpp
frameworks/tomography/Framework/ReconFramework/src/ProjectionReader.cpp
frameworks/tomography/UnitTests/tFrameWork/tst_frameworktest.cpp

Issue456 goldenratio

---

applications/muhrec/src/main.cpp
core/modules/ModuleConfig/include/ConfigBase.h
core/modules/ModuleConfig/src/ConfigBase.cpp
deploy/mac/deploy_muhrec_mac_debug.sh
frameworks/tomography/Backprojectors/StdBackProjectors/src/StdBackProjectorBase.cpp
frameworks/tomography/Framework/ReconFramework/include/processtiminglogger.h
frameworks/tomography/Framework/ReconFramework/qt/ReconFramework/ReconFramework.pro
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Framework/ReconFramework/src/processtiminglogger.cpp
frameworks/tomography/UnitTests/tFrameWork/tst_frameworktest.cpp

Issue468 process timers

---

core/modules/ModuleConfig/include/ProcessModuleBase.h
core/modules/ModuleConfig/src/ProcessModuleBase.cpp
frameworks/tomography/Framework/ReconFramework/include/BackProjectorModuleBase.h
frameworks/tomography/Framework/ReconFramework/include/ReconEngine.h
frameworks/tomography/Framework/ReconFramework/src/BackProjectorModuleBase.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp

Added timer reset for repeated recon.

---

core/algorithms/ImagingAlgorithms/src/StripeFilter.cpp
core/algorithms/ImagingAlgorithms/src/projectionfilter.cpp
core/kipl/UnitTests/tkiplFFT/tkiplFFT.pro
core/kipl/UnitTests/tkiplFFT/tst_kiplfft.cpp
core/kipl/kipl/include/fft/fftbase.h
core/kipl/kipl/src/fft/fftbase.cpp
core/kipl/kipl/src/fft/fftbasef.cpp
core/kiplBundle/kiplBundle.pro

Guarded sections are introduced to protect the FFT initialization. Changed to STL copy and  vectors.

Issue475 thread safe fft

---

core/kipl/UnitTests/tKIPL_IO/tst_tkipl_iotest.cpp
core/kipl/kipl/include/io/io_tiff.h

The unit test says that it should work on the reader level. Let's try and build.

First attempt to fix width error.

---

applications/muhrec/src/fileconversiondialog.cpp
applications/muhrec/src/fileconversiondialog.h
applications/muhrec/src/fileconversiondialog.ui
applications/muhrec/src/muhrec.pro
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/muhrecmainwindow.h
applications/muhrec/src/muhrecmainwindow.ui
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.ui

Added new feature according to issue #504 .

Issue504 fileconvdlg

---

CMakeLists.txt
applications/muhrec/src/referencefiledlg.cpp
core/kipl/kipl/src/interactors/interactionbase.cpp
core/modules/ModuleConfig/include/ProcessModuleBase.h
frameworks/tomography/Backprojectors/StdBackProjectors/CMakeLists.txt
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/include/AdaptiveFilter.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/CameraStripeClean.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/GammaSpotCleanModule.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/GeneralFilter.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/MedianMixRingClean.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/SinoSpotClean.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/TranslateProjectionsModule.h
frameworks/tomography/Preprocessing/StdPreprocModules/src/CameraStripeClean.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/GammaSpotCleanModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/GeneralFilter.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/MedianMixRingClean.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/MorphSpotCleanModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/TranslateProjectionsModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/WaveletRingClean.cpp

Issue403 progressbar

---

applications/muhrec/scripts/PerformanceRecon.xml
applications/muhrec/scripts/makeprojections.py
applications/muhrec/scripts/performance.py
frameworks/tomography/Framework/ReconFramework/include/ReconEngine.h
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp

Fixed the seg fault problem and finalized performance scripts.

Issue530 cl iseg fault

---

CMakeLists.txt
GUI/qt/QtAddons/imageviewerwidget.cpp
GUI/qt/QtAddons/imageviewerwidget.h
applications/imageviewer/CMakeLists.txt
applications/muhrec/src/configuregeometrydialog.cpp
applications/muhrec/src/configuregeometrydialog.h
core/algorithms/ImagingAlgorithms/include/projectionfilter.h
core/algorithms/ImagingAlgorithms/src/ReferenceImageCorrection.cpp
core/algorithms/ImagingAlgorithms/src/projectionfilter.cpp
core/algorithms/UnitTests/tImagingAlgorithms/tst_testImagingAlgorithms.cpp
core/kipl/kipl/include/base/core/timage.hpp
core/kipl/kipl/include/base/timage.h
core/kipl/kipl/include/filters/core/medianfilter.hpp
core/kipl/kipl/include/filters/medianfilter.h
core/kipl/kipl/include/io/io_tiff.h
core/kipl/kipl/include/segmentation/thresholds.h
deploy/mac/deploy_muhrec_mac_arm64.sh
deploy/win/deploymuhrec_cmake.bat
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp.h
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.h
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.h
frameworks/tomography/Framework/ReconFramework/CMakeLists.txt
frameworks/tomography/Framework/ReconFramework/src/ReconHelpers.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/GammaSpotCleanModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/MorphSpotCleanModule.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/bblognorm.cpp
frameworks/tomography/pyMuhRec/CMakeLists.txt

Issue525 m1

---

core/algorithms/ImagingAlgorithms/include/MorphSpotClean.h
core/algorithms/ImagingAlgorithms/src/MorphSpotClean.cpp
core/kipl/UnitTests/tkiplmorphologytest/tkiplmorphologytest.pro
core/kipl/UnitTests/tkiplmorphologytest/tst_kiplmorphologytest.cpp
core/kipl/kipl/include/morphology/core/repairhole.hpp
core/kipl/kipl/include/morphology/repairhole.h
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/morphspotcleandlg.ui

The implementation is successful.

Issue551 spotreplace

---

CMakeLists.txt
applications/muhrec/src/configuregeometrydialog.cpp
applications/muhrec/src/configuregeometrydialog.h
applications/muhrec/src/configuregeometrydialog.ui
core/algorithms/pyadvancedfilters/CMakeLists.txt
core/algorithms/pyimgalg/CMakeLists.txt
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.h
frameworks/tomography/pyMuhRec/CMakeLists.txt

Issue554 centerdlg

---

GUI/qt/QtModuleConfigure/AddModuleDialog.cpp
GUI/qt/QtModuleConfigure/ModuleConfigurator.cpp
GUI/qt/QtModuleConfigure/singlemoduleconfiguratorwidget.cpp
GUI/qt/QtModuleConfigure/singlemodulesettingsdialog.cpp
core/modules/ModuleConfig/src/ModuleItemBase.cpp
frameworks/tomography/Framework/ReconFramework/src/ModuleItem.cpp

Issue fixed and seem to be working on a test system

The load module issue seems to be fixed o windows.

---

CMakeLists.txt
GUI/qt/QtAddons/CMakeLists.txt
GUI/qt/QtAddons/loggingdialog.cpp
GUI/qt/QtAddons/loggingdialog.h
GUI/qt/QtAddons/qtlogviewer.cpp
GUI/qt/QtAddons/qtlogviewer.h
applications/imageviewer/imageviewer/viewermainwindow.cpp
applications/muhrec/src/main.cpp
applications/muhrec/src/muhrecmainwindow.cpp
core/kipl/UnitTests/tLogging/CMakeLists.txt
core/kipl/UnitTests/tLogging/tst_logging.cpp
core/kipl/kipl/include/logging/logger.h
core/kipl/kipl/src/fft/fftbase.cpp
core/kipl/kipl/src/fft/fftbasef.cpp
core/kipl/kipl/src/logging/logger.cpp
deploy/win/deploymuhrec_cmake.bat

Issue558 logstreaming

---

applications/imageviewer/imageviewer/viewermainwindow.cpp
applications/imageviewer/imageviewer/viewermainwindow.h
applications/muhrec/src/muhrecmainwindow.cpp
core/modules/ReaderConfig/analyzefileext.cpp
core/modules/ReaderConfig/analyzefileext.h
core/modules/ReaderConfig/imagewriter.cpp
frameworks/tomography/Framework/ReconFramework/CMakeLists.txt
frameworks/tomography/Framework/ReconFramework/src/ProjectionReader.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp
frameworks/tomography/Framework/ReconFramework/src/ReconHelpers.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/CMakeLists.txt
frameworks/tomography/Preprocessing/StdPreprocModules/src/NormPlugins.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/bblognorm.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/CMakeLists.txt
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/bblognormdlg.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/bblognormdlg.h

Replaced analyse filextension from kipl by readerconfig.
Replaced find("hdf") by analysefileextension.

Issue562 readtiff

---

CMakeLists.txt
GUI/qt/QtModuleConfigure/singlemodulesettingsdialog.cpp
applications/muhrec/src/main.cpp
core/algorithms/ImagingAlgorithms/src/projectionfilter.cpp
core/kipl/UnitTests/tDirAnalysis/CMakeLists.txt
core/kipl/UnitTests/tFillHole/CMakeLists.txt
core/kipl/UnitTests/tImageOperators/CMakeLists.txt
core/kipl/UnitTests/tIndex2Coord/CMakeLists.txt
core/kipl/UnitTests/tKIPL_IO/CMakeLists.txt
core/kipl/UnitTests/tSTLVectorOperations/tst_stlvecoperations.cpp
core/kipl/UnitTests/tedgefunction/CMakeLists.txt
core/kipl/UnitTests/tkiplfilters/CMakeLists.txt
core/kipl/kipl/include/filters/core/filterbase.hpp
deploy/mac/deploy_muhrec_mac_arm64.sh
deploy/win/deploymuhrec_cmake.bat
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.h
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.cpp
frameworks/tomography/Framework/ReconFramework/CMakeLists.txt
frameworks/tomography/Preprocessing/StdPreprocModules/CMakeLists.txt
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/CMakeLists.txt
frameworks/tomography/pyMuhRec/CMakeLists.txt

Crash issue is solved. Added unit tests to the cmake build.

Issue564 fdkcrash

---

CMakeLists.txt
core/kipl/UnitTests/tThreadPool/CMakeLists.txt
core/kipl/UnitTests/tThreadPool/dummyprocessor.cpp
core/kipl/UnitTests/tThreadPool/dummyprocessor.h
core/kipl/UnitTests/tThreadPool/tst_ThreadPool.cpp
core/kipl/kipl/CMakeLists.txt
core/kipl/kipl/include/utilities/threadpool.h
core/kipl/kipl/src/utilities/threadpool.cpp

First working implementation of the thread pool. It still remains to implement as a singleton.

Issue581 threadpool

---

core/kipl/kipl/include/io/io_tiff.h

Fixed the samples per pixel issue

---

core/algorithms/ImagingAlgorithms/src/MorphSpotClean.cpp
core/algorithms/UnitTests/python/testBindMorphSpotClean.py
core/algorithms/pyimgalg/pyMorphSpotClean.cpp

Implemented notebook, fixed bug and revised unit test

Issue601 checkpybind morph spot clean

---

core/algorithms/ImagingAlgorithms/src/StripeFilter.cpp
core/algorithms/UnitTests/python/testBindStripeFilter.py
core/algorithms/pyimgalg/CMakeLists.txt
core/algorithms/pyimgalg/pyStripeFilter.cpp
core/algorithms/pyimgalg/utilities.cpp
core/algorithms/pyimgalg/utilities.h

tested and fixed issues with the stripe clean python binding. Current version is not threaded.

Issue602 check ring clean

---

conanfile.txt
core/kipl/kipl/CMakeLists.txt
frameworks/tomography/Backprojectors/StdBackProjectors/src/MultiProjBPparallel.cpp

The noisy band issue has been resolved.

Issue596 noisybands

---

core/kipl/UnitTests/tkiplbasetest/tst_kiplbase.cpp
core/kipl/kipl/src/base/core/kiplenums.cpp
frameworks/tomography/Backprojectors/StdBackProjectors/src/StdBackProjectorBase.cpp
frameworks/tomography/pyMuhRec/src/pyReconstructor.cpp

It was a copy paste error in the parameter interpretation.

Fixed python parameters for tilt and scan dir in muhrec binding.

---

GUI/qt/QtAddons/plotwidget.cpp
GUI/qt/QtAddons/plotwidget.h
applications/muhrec/src/muhrecmainwindow.cpp
core/kipl/kipl/src/base/core/histogram.cpp
frameworks/tomography/Backprojectors/StdBackProjectors/include/StdBackProjectorBase.h
frameworks/tomography/Backprojectors/StdBackProjectors/src/StdBackProjectorBase.cpp
frameworks/tomography/Framework/ReconFramework/include/ReconEngine.h
frameworks/tomography/Framework/ReconFramework/src/ReconEngine.cpp

Issue46 histogram

---

core/kipl/UnitTests/tThreadPool/dummyprocessor.cpp
core/kipl/UnitTests/tThreadPool/tst_ThreadPool.cpp

The test issue is fixed on ubuntu.

Issue650 t thread test fail

---

core/modules/ModuleConfig/include/ConfigBase.h
core/modules/ModuleConfig/src/ConfigBase.cpp
core/modules/ModuleConfig/src/modulelibnamemanger.cpp
core/modules/UnitTests/tModuleConfig/tst_configbasetest.cpp

Fixed CLI qoutation mark issue and probably the windows failing module manager test.

Issue652 muh cli

---

applications/muhrec/src/muhrecmainwindow.cpp
core/modules/ModuleConfig/src/modulelibnamemanger.cpp
core/modules/UnitTests/tModuleConfig/tst_configbasetest.cpp

Changed hardcoded paths, now it can reconstruct the FITS image.

Changed hardcoded paths

---

core/kipl/kipl/include/morphology/core/morphdist.hpp
core/kipl/kipl/include/morphology/core/morphfilters.hpp
core/kipl/kipl/include/morphology/label.h
core/kipl/kipl/include/morphology/morphfilters.h
core/kipl/kipl/include/morphology/morphology.h
core/kipl/kipl/src/morphology/label.cpp
core/kipl/kipl/src/morphology/morphology.cpp

Fixed a bunch of sign warnings

Issue688 signwarnings

---

applications/imageviewer/CMakeLists.txt
core/kipl/UnitTests/tKIPL_IO/tst_kipl_io.cpp
core/kipl/kipl/include/base/core/sharedbuffer.h
core/kipl/kipl/include/drawing/drawing.h
core/kipl/kipl/include/filters/core/medianfilter.hpp
core/kipl/kipl/include/filters/medianfilter.h
core/kipl/kipl/include/io/io_tiff.h
core/kipl/kipl/src/base/core/imagearithmetics.cpp
core/kipl/kipl/src/math/LUTbase.cpp
core/kipl/kipl/src/math/circularhoughtransform.cpp
core/kipl/kipl/src/math/mathfunctions.cpp
core/kipl/kipl/src/math/median.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.cpp
frameworks/tomography/Backprojectors/StdBackProjectors/src/MultiProjBP.cpp
frameworks/tomography/Backprojectors/StdBackProjectors/src/MultiProjBPparallel.cpp
frameworks/tomography/Backprojectors/StdBackProjectors/src/NNMultiProjBP.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/SpotClean2.cpp

Removed all sse2neon warnings in apple silicon

Issue692 sse2neon

---

applications/muhrec/src/MuhrecInteractor.h
applications/muhrec/src/configuregeometrydialog.h
applications/muhrec/src/piercingpointdialog.h
core/kipl/kipl/include/scalespace/ISSfilter2D.h
core/kipl/kipl/src/math/median.cpp
core/kipl/kipl/src/math/nonlinfit.cpp
core/modules/ReaderGUI/findskiplistdialog.h
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkreconbase.h
frameworks/tomography/Backprojectors/FDKBackProjectors/src/genericbp.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/genericbp.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/AdaptiveFilter.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/BasicRingClean.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/DataScaler.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/ISSfilter.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/NormPlugins.h
frameworks/tomography/Preprocessing/StdPreprocModules/include/TranslatedProjectionWeighting.h
frameworks/tomography/Preprocessing/StdPreprocModules/src/AdaptiveFilter.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/BasicRingClean.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/DataScaler.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/ISSfilter.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/NormPlugins.cpp
frameworks/tomography/Preprocessing/StdPreprocModules/src/TranslatedProjectionWeighting.cpp
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/CMakeLists.txt
frameworks/tomography/Preprocessing/StdPreprocModulesGUI/src/adaptivefilterdlg.cpp

Fixed override/overload warnings.

Issue701 override

---

core/algorithms/UnitTests/tImagingAlgorithms/tst_testImagingAlgorithms.cpp
core/algorithms/UnitTests/tImagingQAAlgorithms/tst_ImagingQAAlgorithms.cpp
core/kipl/UnitTests/tKIPL_IO/tst_kipl_io.cpp
core/kipl/UnitTests/tKiplMath/tst_tkiplmathtest.cpp
core/kipl/UnitTests/tkiplbasetest/tst_kiplbase.cpp
core/kipl/UnitTests/tkiplfilters/tst_kiplfilters.cpp
core/modules/ModuleConfig/src/modulelibnamemanger.cpp
core/modules/UnitTests/tModuleConfig/tst_configbasetest.cpp
core/modules/UnitTests/tReaderConfig/tst_treaderconfigtest.cpp

Updated the test path for linux and macos

Issue680 fixtestpath

---

core/algorithms/AdvancedFilters/ISSfilterQ3D.hpp
core/algorithms/AdvancedFilters/NonLinDiffAOS.h
core/algorithms/AdvancedFilters/diff_filterbase.h
core/algorithms/AdvancedFilters/lambdaest.h

Fixed warning related to advanced filters.

Issue706 clean adv flt

---

core/kipl/kipl/include/io/core/io_generic.hpp
core/kipl/kipl/src/io/core/io_fits.cpp
core/kipl/kipl/src/io/io_nexus.cpp
core/kipl/kipl/src/io/io_png.cpp
core/kipl/kipl/src/math/nonlinfit.cpp
core/modules/ReaderConfig/imagereader.cpp
core/modules/ReaderGUI/findskiplistdialog.cpp
core/modules/ReaderGUI/findskiplistdialog.ui

The reader related warnings are fixed.

Issue708 reader warn

---

GUI/qt/QtAddons/comparevolumeviewer.cpp
GUI/qt/QtAddons/imagepainter.h
GUI/qt/QtAddons/imageviewerwidget.cpp
GUI/qt/QtAddons/plotpainter.h
GUI/qt/QtAddons/reportgeneratorbase.cpp
GUI/qt/QtAddons/roimanager.cpp

Issue712 warn qt addons

---

core/algorithms/ImagingAlgorithms/include/ReplaceUnderexposed.h
core/algorithms/ImagingAlgorithms/src/MorphSpotClean.cpp
core/algorithms/ImagingAlgorithms/src/ReferenceImageCorrection.cpp
core/algorithms/ImagingAlgorithms/src/ReplaceUnderexposed.cpp
core/algorithms/ImagingAlgorithms/src/SpotClean.cpp
core/algorithms/ImagingAlgorithms/src/TranslateProjections.cpp
core/algorithms/ImagingAlgorithms/src/averageimage.cpp
core/algorithms/ImagingAlgorithms/src/normalizeimage.cpp
core/algorithms/ImagingAlgorithms/src/piercingpointestimator.cpp
core/algorithms/ImagingAlgorithms/src/tomocenter.cpp
core/algorithms/UnitTests/tImagingAlgorithms/tst_testImagingAlgorithms.cpp
core/kipl/kipl/include/morphology/core/morphextrema.hpp

Fixed warnings in Imaging algorithms

Issue711 imgalg warn

---

core/kipl/UnitTests/tKiplMath/tst_tkiplmathtest.cpp

Fixed failing test in mathtests on ubuntu.

Issue729 math test

---

applications/CLI/muhrecCLI/muhreccli.cpp

Updated path slash of the application

---

core/kipl/UnitTests/tThreadPool/tst_ThreadPool.cpp
core/kipl/kipl/include/utilities/threadpool.h

Implemented a threaded transform function in the pool.

Issue746 transform

---

frameworks/tomography/pyMuhRec/src/pyReconstructor.cpp

The missing Algorithm parameter was added as an internal hard-coded parameter.

Added the missing parameter

---

README.md

Just updating the README.MD python badge with the new supported versions.

Update python badge with supported versions

---

CMakeLists.txt
applications/CLI/multiframesplitter/CMakeLists.txt
applications/CLI/multiframesplitter/main.cpp
core/kipl/kipl/include/math/core/image_statistics.hpp
core/kipl/kipl/include/math/image_statistics.h

Created a CMake file and removed Qt dependencies.

Cmake build of frame splitter complete. 

---

GUI/qt/QtAddons/qtlogviewer.ui
applications/CLI/muhrecCLI/main.cpp
applications/CLI/muhrecCLI/muhreccli.cpp
applications/muhrec/src/main.cpp
applications/muhrec/src/muhrecmainwindow.cpp
applications/muhrec/src/preferencesdialog.cpp
applications/muhrec/src/preferencesdialog.ui
core/kipl/UnitTests/tLogging/tst_logging.cpp
core/kipl/kipl/include/logging/logger.h
core/kipl/kipl/src/logging/logger.cpp

Most items of issue #804 have been solved
Adding log level control to the Python binding doesn't make sense yet.

Issue804 loglevel

---

frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.cpp
frameworks/tomography/Backprojectors/FDKBackProjectors/src/fdkbp_single.h
frameworks/tomography/UnitTests/tFDKBackProjectors/tst_FDKBackprojectors.cpp

Updated defaults for interpolation and added unit tests for enums

Renamed enum strings and changed defaults.
